export const INITIALISE_APPLICATION = 'INITIALISE_APPLICATION'
export const UPDATE_TIME = 'UPDATE_TIME'

///////////////////////////////

// notifications
export const SET_CURRENT_NOTIFICATION = 'SET_CURRENT_NOTIFICATION'
export const CLEAR_CURRENT_NOTIFICATION = 'CLEAR_CURRENT_NOTIFICATION'
export const INITIALISE_NOTIFICATIONS = 'INITIALISE_NOTIFICATIONS'
export const WAIT_FOR_NOTIFICATIONS_WORKER_INITIALISATION = 'WAIT_FOR_NOTIFICATIONS_WORKER_INITIALISATION'
export const ACKNOWLEDGE_NOTIFICATIONS_WORKER_INITIALISED = 'ACKNOWLEDGE_NOTIFICATIONS_WORKER_INITIALISED'
export const SET_NOTIFICATIONS_STATUS = 'SET_NOTIFICATIONS_STATUS'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const REQUEST_NEW_NOTIFICATION_AGGREGATION = 'REQUEST_NEW_NOTIFICATION_AGGREGATION'
