export const SET_DAILY_STATUS = 'SET_DAILY_STATUS'
export const GET_DAILY = 'GET_DAILY'
export const SET_DAILY = 'SET_DAILY'
export const REQUEST_NEW_DAILY_AGGREGATION = 'REQUEST_NEW_DAILY_AGGREGATION'
