export const INITIALISE = 'INITIALISE'
export const INITIALISATION_COMPLETE = 'INITIALISATION_COMPLETE'

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'

export const CHANGE_AGGREGATION = 'CHANGE_AGGREGATION'
